export interface ReplayViewerDeps {
  createWebviewPanel: (
    viewType: string,
    title: string,
    showOptions: number,
    options: { enableScripts: boolean; localResourceRoots?: { fsPath: string }[] },
  ) => WebviewPanel;
  readFile: (path: string) => Promise<string>;
  showInformationMessage: (msg: string) => void;
}

export interface Webview {
  html: string;
  cspSource: string;
}

export interface WebviewPanel {
  webview: Webview;
  reveal: () => void;
  onDidDispose: (cb: () => void) => void;
  dispose: () => void;
}

export class ReplayViewerPanel {
  private _panel: WebviewPanel | undefined;
  private readonly _deps: ReplayViewerDeps;
  private _currentFolderUri: string | undefined;

  constructor(deps: ReplayViewerDeps) {
    this._deps = deps;
  }

  get currentFolderUri(): string | undefined {
    return this._currentFolderUri;
  }

  get visible(): boolean {
    return this._panel !== undefined;
  }

  async reveal(replayPath: string, claudeloopRoot: string, folderUri?: string): Promise<void> {
    this._currentFolderUri = folderUri;
    let html: string;
    try {
      html = await this._deps.readFile(replayPath);
    } catch {
      this._deps.showInformationMessage("No replay available");
      return;
    }

    if (this._panel) {
      this._panel.reveal();
    } else {
      this._panel = this._deps.createWebviewPanel(
        "oxveil.replayViewer",
        "Replay",
        1, // ViewColumn.One
        {
          enableScripts: true,
          localResourceRoots: [{ fsPath: claudeloopRoot }],
        },
      );
      this._panel.onDidDispose(() => {
        this._panel = undefined;
      });
    }

    this._panel.webview.html = this._injectSecurity(html, this._panel.webview.cspSource);
  }

  dispose(): void {
    this._panel?.dispose();
    this._panel = undefined;
  }

  /** Visible for testing */
  get panel(): WebviewPanel | undefined {
    return this._panel;
  }

  private _injectSecurity(html: string, cspSource: string): string {
    // replay.html is trusted local content generated by claudeloop.
    // It uses inline event handlers (onclick, onkeydown) extensively,
    // which cannot be covered by nonces. Use 'unsafe-inline' for scripts
    // and styles since the content is not user-supplied.
    const cspTag = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${cspSource} 'unsafe-inline'; script-src 'unsafe-inline'; img-src ${cspSource} data:;">`;
    if (/<head[^>]*>/i.test(html)) {
      return html.replace(/(<head[^>]*>)/i, `$1\n  ${cspTag}`);
    }
    return cspTag + "\n" + html;
  }
}
